name: Daily Job

on:
  workflow_dispatch: # Дозволяє ручний запуск
  schedule:
    - cron: '39 9 * * *' # Запуск щодня о 09:35 UTC (10:35 Берліну)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run the script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          URL: ${{ secrets.URL }}
        run: node script.js
